### ISSUE TITLE
go make-coffee roud robin seems stuck?

### ISSUE THREAD

**Issue by mikemountjoy99** [craigmayhew/dns-adventure-game#1]
go make-coffee seems to only ever return one message even though the zone file contains three different entries?

date
Fri 10 Jan 2020 10:53:10 GMT
sh-3.2$ go make-coffee

You go make a coffee, only to find there is none. Realising the futility of attempting to function without a minimum of 30mg of caffeine sloshing around your blood stream, you walk out the building. You are no longer playing the game.

sh-3.2$ date
Fri 10 Jan 2020 10:53:52 GMT
sh-3.2$ go make-coffee

You go make a coffee, only to find there is none. Realising the futility of attempting to function without a minimum of 30mg of caffeine sloshing around your blood stream, you walk out the building. You are no longer playing the game.

sh-3.2$ date
Fri 10 Jan 2020 10:54:05 GMT
sh-3.2$ go make-coffee

You go make a coffee, only to find there is none. Realising the futility of attempting to function without a minimum of 30mg of caffeine sloshing around your blood stream, you walk out the building. You are no longer playing the game.

This is a really good demo of DNS Pipelining.

**Comment by craigmayhew** [comment]
Thanks for reporting this.

The dig command was returning all 3 values for the record, and then just the final one was being used. This has now been corrected by introducing `| shuf -n 1` to randomly pick one of the outcomes. It's a shame it's not using round robin DNS for the TXT record.

d68a22bf8a78c611083ca6f6406a116927592378 fixes the issue.
